siwookim97/ecomm-hub

src/main/java/com/likelion/ecommhub/domain/MailDto.java
src/main/java/com/likelion/ecommhub/service/MailService.java
src/main/resources/static/resource/mailForm.css
src/main/resources/static/resource/mailForm.js
src/main/resources/static/resource/mailSent.css
src/main/resources/templates/mailForm.html
src/main/resources/templates/mailSent.html
src/test/java/com/likelion/ecommhub/Service/MailServiceTest.java

close #15 
- 여러명에게 메일을 보낼 수 있도록 메일 폼 수정
- MailDto에서 address를 String배열로 변경
- MailService 및 테스트케이스 수정

fix: 메일 폼 수정 및 메일 Service 수정

---

src/main/java/com/likelion/ecommhub/controller/MemberController.java
src/main/java/com/likelion/ecommhub/domain/Photo.java
src/main/java/com/likelion/ecommhub/repository/PhotoRepository.java

close #13 
- Photo Entity 추가
- 사진을 localStorage에 추가하는 기능 추가
- Photo Service단 추가

Product Entity에 들어갈 Photo Entity 기능 구현

---

src/main/java/com/likelion/ecommhub/dto/ProductDto.java
src/main/java/com/likelion/ecommhub/repository/MemberRepository.java
src/main/java/com/likelion/ecommhub/service/MemberService.java
src/main/java/com/likelion/ecommhub/service/ProductService.java

상품 등록기능 수정

---

src/main/java/com/likelion/ecommhub/service/CartService.java
src/main/java/com/likelion/ecommhub/service/MailService.java
src/main/resources/application.yml
src/main/resources/static/resource/style.css
src/main/resources/templates/cartList.html

fix: 장바구니 view 페이지 수정

---

src/main/java/com/likelion/ecommhub/controller/MailController.java
src/main/java/com/likelion/ecommhub/dto/MailDto.java
src/main/java/com/likelion/ecommhub/service/MailService.java
src/main/resources/templates/product/enroll.html
src/test/java/com/likelion/ecommhub/Service/MailServiceTest.java

close #31 
- 제품 등록 페이지 수정
- 제품 이미지 1개 띄우기 기능 추가

제품 등록기능 View 페이지 수정

---

src/main/java/com/likelion/ecommhub/controller/ProductController.java
src/main/java/com/likelion/ecommhub/domain/Cart.java
src/main/java/com/likelion/ecommhub/service/ProductService.java
src/main/resources/templates/product/home.html

close #37 
- 상품 이름 검색에 따른 결과 출력 기능 추가
- 고려할 특이사항
1. 검색 필드 및 검색어 정규화
2. 검색 결과 정렬

검색 기능 추가 #37

---

src/main/java/com/likelion/ecommhub/controller/InquiryController.java
src/main/java/com/likelion/ecommhub/controller/ReviewController.java
src/main/java/com/likelion/ecommhub/domain/Product.java
src/main/java/com/likelion/ecommhub/initData/NotProd.java
src/main/resources/templates/inquiry/enroll.html
src/main/resources/templates/product/home.html
src/main/resources/templates/review/enroll.html

close #45 
- 문의 페이지 추가
- 리뷰 페이지 추가

문의, 리뷰 페이지

---

src/main/java/com/likelion/ecommhub/controller/NoticeController.java
src/main/java/com/likelion/ecommhub/domain/Notice.java
src/main/java/com/likelion/ecommhub/domain/NoticeType.java
src/main/java/com/likelion/ecommhub/dto/NoticeDto.java
src/main/java/com/likelion/ecommhub/repository/NoticeRepository.java
src/main/java/com/likelion/ecommhub/service/NoticeService.java
src/main/resources/templates/notice/edit-form.html
src/main/resources/templates/notice/form.html
src/main/resources/templates/notice/list.html
src/test/java/com/likelion/ecommhub/Service/NoticeServiceTest.java
src/test/java/com/likelion/ecommhub/repository/NoticeRepositoryTest.java

close #25 
-공지사항 등록
-공지사항 수정
-공지사항 삭제
-UI

시스템 공지사항 기능 추가 #25

---

build.gradle
src/main/java/com/likelion/ecommhub/controller/InquiryController.java
src/main/java/com/likelion/ecommhub/controller/OrderController.java
src/main/java/com/likelion/ecommhub/controller/ProductController.java
src/main/java/com/likelion/ecommhub/domain/Member.java
src/main/java/com/likelion/ecommhub/domain/Order.java
src/main/java/com/likelion/ecommhub/domain/OrderItem.java
src/main/java/com/likelion/ecommhub/domain/Product.java
src/main/java/com/likelion/ecommhub/initData/NotProd.java
src/main/java/com/likelion/ecommhub/repository/OrderItemRepository.java
src/main/java/com/likelion/ecommhub/repository/OrderRepository.java
src/main/java/com/likelion/ecommhub/service/CartService.java
src/main/java/com/likelion/ecommhub/service/MemberService.java
src/main/java/com/likelion/ecommhub/service/OrderService.java
src/main/resources/static/resource/style.css
src/main/resources/templates/cart.html
src/main/resources/templates/fragments/footer.html
src/main/resources/templates/fragments/header.html
src/main/resources/templates/orderList.html
src/test/java/com/likelion/ecommhub/Service/ProductServiceTest.java
src/test/java/com/likelion/ecommhub/repository/MemberRepositoryTest.java

주문내역 및 카카오 결제창

---

src/main/java/com/likelion/ecommhub/service/CartService.java
src/main/resources/templates/cart.html

장바구니 삭제 기능 오류 수정

---

build.gradle
src/main/java/com/likelion/ecommhub/config/JpaConfig.java
src/main/java/com/likelion/ecommhub/controller/CartController.java
src/main/java/com/likelion/ecommhub/controller/OrderController.java
src/main/java/com/likelion/ecommhub/domain/Cart.java
src/main/java/com/likelion/ecommhub/domain/CartItem.java
src/main/java/com/likelion/ecommhub/domain/Member.java
src/main/java/com/likelion/ecommhub/domain/Order.java
src/main/java/com/likelion/ecommhub/domain/OrderItem.java
src/main/java/com/likelion/ecommhub/domain/Product.java
src/main/java/com/likelion/ecommhub/dto/MemberJoinDto.java
src/main/java/com/likelion/ecommhub/initData/NotProd.java
src/main/java/com/likelion/ecommhub/repository/OrderItemRepository.java
src/main/java/com/likelion/ecommhub/service/CartService.java
src/main/java/com/likelion/ecommhub/service/MemberService.java
src/main/java/com/likelion/ecommhub/service/OrderService.java
src/main/resources/templates/cart.html
src/main/resources/templates/fragments/header.html
src/main/resources/templates/orderList.html
src/test/java/com/likelion/ecommhub/Service/ProductServiceTest.java
src/test/java/com/likelion/ecommhub/repository/MemberRepositoryTest.java
src/test/java/com/likelion/ecommhub/service/MemberServiceTest.java

close #58 
- 구매버튼 클릭시 결제 창 활성화 및 주문 내역 업데이트
- 구매 버튼 type=”button” 일 경우 form전송이 안되고 type=”submit” 일 경우 결제 기능이 작동하지 않는 오류가 발생했으나 submit을 사용하는 대신 ajax, json을 사용하여 해결

구매 버튼 클릭시 결제 진행 및 주문 내역 업데이트

---

build.gradle
src/main/java/com/likelion/ecommhub/controller/ProductController.java
src/main/java/com/likelion/ecommhub/domain/Image.java
src/main/java/com/likelion/ecommhub/domain/Product.java
src/main/java/com/likelion/ecommhub/dto/ProductDto.java
src/main/java/com/likelion/ecommhub/dto/ProductSearchResult.java
src/main/java/com/likelion/ecommhub/repository/ProductRepositoryImpl.java
src/main/java/com/likelion/ecommhub/service/ImageService.java
src/main/java/com/likelion/ecommhub/util/Ut.java
src/main/resources/templates/product/enroll.html
src/main/resources/templates/product/home.html

close #80 
- Product 엔티티와 Image 엔티티 OneToOne 연관관계로 변경
- 엔티티 구조 변경에 따른 로직 수정
- /product/home 페이지에 이미지를 띄워주는 코드 변경
- 회원가입 페이지 명확한 분리, view template 변경

Product 엔티티와 Image 엔티티 연관관계 리팩토링

---

build.gradle
src/main/java/com/likelion/ecommhub/controller/CartController.java
src/main/java/com/likelion/ecommhub/controller/MemberController.java
src/main/java/com/likelion/ecommhub/controller/ProductController.java
src/main/java/com/likelion/ecommhub/repository/ReviewRepository.java
src/main/java/com/likelion/ecommhub/service/CartService.java
src/main/java/com/likelion/ecommhub/service/ReviewService.java
src/main/resources/static/resource/style.css
src/main/resources/templates/fragments/header.html
src/main/resources/templates/product/enroll.html
src/main/resources/templates/product/productView.html
src/main/resources/templates/review/enroll.html
src/main/resources/templates/usr/member/cart.html
src/main/resources/templates/usr/member/memberPage.html

제품 이름, 설명, 재고
장바구니에 담기 기능으로 가는 버튼
판매자 이름 -> 클릭시 판매자 정보 페이지로 이동
리뷰 아래에 띄워주기
문의 & 리뷰 버튼 해당 페이지로 이동
/product/list 제품 메인 페이지에서 이동하는 페이지 -> Property or field 'bucketObjectUrl' cannot be found on null 오류로 인해list페이지에 접속 불가
review TODO 채우기

제품 상세 페이지 구현

---

src/main/java/com/likelion/ecommhub/config/auth/AuthenticationConfig.java
src/main/java/com/likelion/ecommhub/controller/CartController.java
src/main/java/com/likelion/ecommhub/controller/MemberController.java
src/main/java/com/likelion/ecommhub/controller/NoticeController.java
src/main/java/com/likelion/ecommhub/controller/ProductController.java
src/main/java/com/likelion/ecommhub/domain/Member.java
src/main/java/com/likelion/ecommhub/dto/MemberJoinDto.java
src/main/java/com/likelion/ecommhub/initData/NotProd.java
src/main/java/com/likelion/ecommhub/service/MemberService.java
src/main/resources/templates/usr/member/join.html
src/main/resources/templates/usr/member/loginSuccess.html

merge 과정에서 발생한 build 문제 수정

---

src/main/java/com/likelion/ecommhub/controller/OrderController.java
src/main/java/com/likelion/ecommhub/controller/ProductController.java
src/main/java/com/likelion/ecommhub/service/MemberService.java
src/main/resources/templates/fragments/header.html

close #90 
BUYER로 로그인 했을때
SELLER로 로그인 했을때
로그인 안했을때
- 로그인 안했을때 orderList페이지로 접속하면 로그인페이지로 넘어감 -> 이유를 모르겠음
- 장바구니 UI 수정 후 구매하기 기능 수정 예정

url에 사용자 id 숨김, 권한 설정

---

src/main/java/com/likelion/ecommhub/controller/CartController.java
src/main/java/com/likelion/ecommhub/service/MemberService.java
src/main/java/com/likelion/ecommhub/service/ProductService.java
src/main/resources/templates/usr/member/cart.html

- 장바구니 url 수정
- 구매하기 버튼 기능은 member/cart.html 를 usr/member/cart.html 로 옮기면서 생긴 오류
- close #88

장바구니 url 수정 &구매하기 버튼 기능

---

src/main/java/com/likelion/ecommhub/config/auth/AuthenticationConfig.java
src/main/java/com/likelion/ecommhub/controller/MemberController.java
src/main/java/com/likelion/ecommhub/controller/OrderController.java
src/main/java/com/likelion/ecommhub/controller/ProductController.java
src/main/java/com/likelion/ecommhub/domain/Member.java
src/main/java/com/likelion/ecommhub/service/MemberService.java
src/main/java/com/likelion/ecommhub/service/OrderService.java
src/main/resources/templates/usr/member/memberModify.html
src/main/resources/templates/usr/member/memberPage.html

close #89 
- MemberController 권한 부여
- 새로 가입한 회원의 myPage가 작동하지 않는 문제 수정
- 프로젝트 전체적인 코드 스타일, 권한 수정

MemberController 권한 수정, myPage 작동하지 않는 문제 수정

---

src/main/java/com/likelion/ecommhub/controller/NoticeController.java
src/main/java/com/likelion/ecommhub/domain/MemberRole.java
src/main/java/com/likelion/ecommhub/initData/NotProd.java
src/main/resources/templates/notice/list.html
src/main/resources/templates/orderList.html
src/main/resources/templates/usr/member/memberModify.html
src/main/resources/templates/usr/member/memberPage.html

close #99 
- ROLE_ADMIN만 등록, 수정, 삭제 가능
- 그 외에는 버튼이 안보임

notice 권한 설정

---

src/main/java/com/likelion/ecommhub/controller/CartController.java
src/main/java/com/likelion/ecommhub/controller/OrderController.java
src/main/java/com/likelion/ecommhub/controller/SalesController.java
src/main/java/com/likelion/ecommhub/domain/Inquiry.java
src/main/java/com/likelion/ecommhub/domain/Notice.java
src/main/java/com/likelion/ecommhub/domain/Order.java
src/main/java/com/likelion/ecommhub/dto/MemberLoginDto.java
src/main/java/com/likelion/ecommhub/dto/ProductSearchCondition.java
src/main/java/com/likelion/ecommhub/dto/ProductSearchResult.java
src/main/java/com/likelion/ecommhub/dto/SalesDto.java
src/main/java/com/likelion/ecommhub/repository/CartRepository.java
src/main/java/com/likelion/ecommhub/service/CartService.java
src/main/java/com/likelion/ecommhub/service/ImageService.java
src/main/java/com/likelion/ecommhub/service/MailService.java
src/main/java/com/likelion/ecommhub/service/MemberService.java
src/main/java/com/likelion/ecommhub/service/ReviewService.java
src/main/java/com/likelion/ecommhub/service/SalesService.java
src/main/resources/messages.properties
src/main/resources/templates/orderList.html
src/main/resources/templates/product/productView.html
src/main/resources/templates/usr/layout/layout.html

close #97 
- 프로젝트 코드 스타일 수정
- 프로젝트 전체적인 권한 수정

프로젝트 전체적인 코드 스타일, 권한 수정

---

src/main/java/com/likelion/ecommhub/controller/CartController.java
src/main/resources/application.yml
src/main/resources/static/resource/common/common.js
src/main/resources/templates/product/productView.html
src/main/resources/templates/usr/member/cart.html

- 상세페이지에서 모달띄워주기
- 장바구니 페이지에서도 페이지 유지하도록 수정
- close #102

제품상세페이지에서 모달띄워주기

---

src/main/resources/templates/usr/member/join.html
src/main/resources/templates/usr/member/joinBuyer.html
src/main/resources/templates/usr/member/joinSeller.html
src/main/resources/templates/usr/member/login.html

close #109 
- 네비게이션 바 폼 추가수정
- 회원가입, 로그인 버튼 색상 변경
- 전화번호 입력 숫자, 11글자만 입력이 가능하도록 수정
- 제품 페이지 폼 수정

네비게이션 바 폼 추가수정

---

src/main/resources/templates/product/home.html
src/main/resources/templates/usr/layout/layout.html

close #114 
- 페이지네이션 버튼은 바꿀만한게 딱히 모르겠어서 그냥 놔뒀습니다

home view수정

---

src/main/resources/templates/common/layout.html
src/main/resources/templates/fragments/footer.html
src/main/resources/templates/inquiry/enroll.html
src/main/resources/templates/product/productView.html
src/main/resources/templates/review/enroll.html
src/main/resources/templates/usr/layout/layout.html

close #120 
footer 공간 없애기
제품 상세 페이지
문의
리뷰

제품 상세, 문의, 리뷰 view 수정, footer 수정

---

src/main/resources/templates/product/home.html

close #117 
- 제품 페이지 폼 수정
- 구매자일때 네비게이션 바에 장바구니로 가는 버튼 추가
- 상단 네비게이션바 검색 폼 수정

제품 페이지 폼 수정

---

src/main/java/com/likelion/ecommhub/dto/ProductSearchCondition.java
src/main/java/com/likelion/ecommhub/repository/ProductRepositoryImpl.java
src/main/resources/templates/common/layout.html
src/main/resources/templates/product/home.html
src/main/resources/templates/usr/layout/layout.html

close #126 
- 네비게이션 바 수정
- 검색 로직 수정
- 메인화면 상품 이름 폼 수정
- 상품 상세설명 줄바꿈
- 판매자 정보 추가

네비게이션 바 장바구니 버튼 추가, 검색 로직 변경

---

src/main/resources/templates/common/layout.html
src/main/resources/templates/notice/edit-form.html
src/main/resources/templates/notice/form.html
src/main/resources/templates/notice/list.html
src/main/resources/templates/product/enroll.html
src/main/resources/templates/product/productView.html
src/main/resources/templates/usr/layout/layout.html
src/main/resources/templates/usr/member/cart.html
src/main/resources/templates/usr/member/joinBuyer.html
src/main/resources/templates/usr/member/joinSeller.html
src/main/resources/templates/usr/member/login.html
src/main/resources/templates/usr/member/memberModify.html
src/main/resources/templates/usr/member/memberPage.html
src/main/resources/templates/usr/member/orderList.html

close #127 
- 하단 바 글자 색, 크기 통일
- 회원 수정 페이지 UI 적용

하단 바 글자 흰색으로 통일

---

src/main/java/com/likelion/ecommhub/controller/MemberController.java
src/main/java/com/likelion/ecommhub/dto/MemberModifyDto.java
src/main/java/com/likelion/ecommhub/service/MemberService.java
src/main/resources/templates/usr/member/memberModify.html
src/main/resources/templates/usr/member/memberPage.html

close #129 
Member의 id를 이용한 url 제거 
MemberModifyDto를 사용하였습니다

회원 정보 수정 URL과 DTO 도입

---

src/main/resources/templates/usr/member/cart.html

close #135 
- 구매하기 버튼 클릭 후 주문내역으로 이동
- 구매하기 후 장바구니 상품들 삭제

구매하기 버튼 클릭 후 주문 내역으로 이동

---

src/main/java/com/likelion/ecommhub/controller/OrderController.java
src/main/java/com/likelion/ecommhub/service/MemberService.java
src/main/resources/templates/usr/member/cart.html
src/main/resources/templates/usr/member/orderList.html

close #139 
- orderList에 데이터가 출력되기까지 시간이 좀 걸리는거 같습니다 (페이지 이동까지 2초 정도 시간텀을 두면 제대로 출력)
- 일단 myPage로 가는걸로 수정

구매자 회원가입 후 장바구니 접속이 안되는 오류, 구매하고 주문 내역 갱신되지 않음(새로고침 필요) 수정

---

src/main/resources/templates/usr/member/cart.html

close #138
- 장바구니 UI 수정
- 장바구니 가격 콤마 포멧 추가
- 로그인, 로그아웃, 문의, 리뷰 view 폼 수정
- 리뷰 주문목록 로직 추가

장바구니 UI 수정

---

src/main/java/com/likelion/ecommhub/dto/MemberModifyDto.java
src/main/resources/templates/usr/member/memberModify.html

close #134 
수정 form에 입력되지 않아도 기존 값 저장
th:value ~ ? ~  사용
버튼 변경

회원 정보 수정 form 변경

---

src/main/java/com/likelion/ecommhub/controller/MemberController.java
src/main/java/com/likelion/ecommhub/controller/ProductController.java
src/main/java/com/likelion/ecommhub/controller/ReviewController.java
src/main/java/com/likelion/ecommhub/domain/Member.java
src/main/java/com/likelion/ecommhub/dto/MemberModifyDto.java
src/main/java/com/likelion/ecommhub/repository/ReviewRepository.java
src/main/java/com/likelion/ecommhub/service/MemberService.java
src/main/java/com/likelion/ecommhub/service/ReviewService.java
src/main/resources/templates/product/home.html
src/main/resources/templates/usr/member/memberModify.html

close #145 
- 장바구니 UI 수정
- 장바구니 가격 콤마 포멧 추가

리뷰 검증로직 추가, 회원 수정 폼 변경

---

src/main/java/com/likelion/ecommhub/controller/MemberController.java
src/main/java/com/likelion/ecommhub/controller/ReviewController.java
src/main/resources/templates/product/enroll.html
src/main/resources/templates/product/home.html
src/main/resources/templates/product/productView.html
src/main/resources/templates/usr/member/sellerInfo.html

close #152 
- 제품 메인 페이지 상품 등록 버튼 UI 수정
- 제품 상세 페이지 폼 변경
- 제품 등록기능 검증 script 추가 (이름, 가격, 설명, 수량 필수 입력값)
- 리뷰 등록, 문의 등록 view 수정

제품 상세 페이지 UI 수정, 제품 등록 

---

src/main/resources/templates/notice/form.html
src/main/resources/templates/notice/list.html

-공지 리스트[admin]
-공지 리스트[seller]
-등록폼

공지사항 UI 변경

---

src/main/java/com/likelion/ecommhub/controller/ErrorController.java
src/main/java/com/likelion/ecommhub/controller/InquiryController.java
src/main/java/com/likelion/ecommhub/controller/MemberController.java
src/main/java/com/likelion/ecommhub/service/ReviewService.java
src/main/java/com/likelion/ecommhub/util/GlobalExceptionHandler.java
src/main/resources/templates/inquiry/enroll.html
src/main/resources/templates/review/enroll.html

close #155 
- 리뷰
- post form UI 수정
- 리뷰 from 검증 script 추가
- 구매를 하지 않은 사용자가 리뷰를 달 경우 에러 페이지 출력
- 문의 
- post form UI 수정
- 문의 form 검증 script 추가
- 로그인, 회원가입 등등 등록 form 검증 script 추가

리뷰 등록, 문의 등록 view 수정, 검증

---

src/main/java/com/likelion/ecommhub/controller/ErrorController.java
src/main/java/com/likelion/ecommhub/controller/InquiryController.java
src/main/java/com/likelion/ecommhub/controller/MemberController.java
src/main/java/com/likelion/ecommhub/service/ReviewService.java
src/main/java/com/likelion/ecommhub/util/GlobalExceptionHandler.java
src/main/resources/templates/error/400.html
src/main/resources/templates/inquiry/enroll.html
src/main/resources/templates/review/enroll.html
src/main/resources/templates/usr/member/joinBuyer.html
src/main/resources/templates/usr/member/joinSeller.html

close #161 
- 회원가입
- form 검증 script 추가
- 로그인
- 로그인 실패시 해당 페이지로 redirect 해주기에 추가하지 않음  
- 문의 리스트 페이지 생성

회원가입 등록 form 검증 script 추가

---

src/main/resources/templates/usr/member/memberPage.html

사용자 정보 구매 list 추가

---

src/main/java/com/likelion/ecommhub/controller/CartController.java
src/main/java/com/likelion/ecommhub/controller/OrderController.java
src/main/java/com/likelion/ecommhub/service/CartService.java
src/main/java/com/likelion/ecommhub/service/MemberService.java
src/main/resources/templates/usr/member/cart.html

close #150 
- 장바구니 페이지에서 구매버튼 누르면 결제 후 주문내역에 내용 출력
- ordercontroller의 cartCheckout 메서드에 있는 sale 부분에 오류가 발생해 잠시 비활성화

장바구니 페이지 수정

---

src/main/resources/templates/usr/member/memberPage.html

리뷰/문의 버튼 이동 구현
